robotic_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_stand1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: stand1_to_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: stand2_to_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: stand3_to_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}